### ISSUE TITLE
Mood out of range in Tarragona

### ISSUE THREAD

**Issue by danielredondo** [perakakis/CoVidAffect#1]
Nice project you have here, congratulations!

Browsing the webpage https://covidaffect.info I found a small bug with Tarragona, where the mood is -10,10 (incompatible with range being between -10 and 10). See image attached below.

![Anotación 2020-09-07 115652](https://user-images.githubusercontent.com/18743806/93181022-3b19d780-f738-11ea-8614-9690baabd823.png)

Diving in the data, I didn't find anything unusual, but I'm no expert in the project. There's only one participant in Tarragona (id 1178, with 2 entries in mood.csv) but the data seems pretty normal to me.

**Comment by danielredondo** [comment]
Apparently it's also happening in other areas...

<img width="317" alt="" src="https://user-images.githubusercontent.com/18743806/93663562-3a9b7c80-fa69-11ea-983a-204b8f731967.png">

<img width="286" alt="" src="https://user-images.githubusercontent.com/18743806/93663566-40915d80-fa69-11ea-934f-8e0222547edd.png">

<img width="322" alt="" src="https://user-images.githubusercontent.com/18743806/93663580-4edf7980-fa69-11ea-9828-220bda2fb036.png">

**Comment by perakakis** [comment]
Hi Daniel and thank you for your kind words and for the observation.

The mood data on the map represent changes in mood compared to a pre-lockdown baseline reported in the initial questionnaire. So actually they can take values from -20 to +20. For example if a participant reports that his/her mood before lockdown was +10 and then during lockdown records a value of -10, the map would display the difference current_value-baseline_value: -10-(+10)=-20. So, if there is a problem you can say that it is with the colorbar that indicates a possible range between -10 and 10. To be more accurate this should be -20 to +20. However, since extreme values below -10 or +10 are rare, especially when averaging across several subjects, and so that we can have higher resolution in the map to distinguish between differences across provinces, we decided to use a reduced colorbar range.

Thank you again for the observation. In the dataset that is available for download, mood data are raw and the baseline is given as a separate variable so that users can do any calculation they consider pertinent.

**Comment by danielredondo** [comment]
Thanks @perakakis for replying! I didn't interpret the mood in the right way, thanks for clarifying.

The (small) issue seems to be that the legend can be confusing because it doesn't contain all the posible values of the map. I would suggest using something like this:

<img width="801" alt="Captura de pantalla 2020-09-19 a las 14 26 45" src="https://user-images.githubusercontent.com/18743806/93667248-a5a67c80-fa84-11ea-8c1d-2a7c5e746e40.png">

And it can improve by:

- changing the title of the colorbar: mood ("Estado de ánimo") can be replaced with change in mood ("Cambio en estado de ánimo").

- adding more intermediate values in the colorbar (e.g. 5) - to see that the scale is linear until 10 and then values between 10 and 20 get the same color.

Anyway, just some suggestions! I'm closing the issue, thanks for your time!
